// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $b_id_ from "./routes/b/[id].tsx";
import * as $button_lab from "./routes/button-lab.tsx";
import * as $index from "./routes/index.tsx";
import * as $ButtonStudio from "./islands/ButtonStudio.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/b/[id].tsx": $b_id_,
    "./routes/button-lab.tsx": $button_lab,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ButtonStudio.tsx": $ButtonStudio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
